# Generated by Django 6.0.1 on 2026-01-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total da venda",
                        max_digits=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("sale_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="sales_sale_company_328b30_idx"
                    ),
                    models.Index(
                        fields=["sale_date"], name="sales_sale_sale_da_2fd927_idx"
                    ),
                    models.Index(
                        fields=["product"], name="sales_sale_product_d1188a_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="sales_sale_custome_f0dcab_idx"
                    ),
                ],
            },
        ),
    ]
