# Generated by Django 6.0.1 on 2026-01-16 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor total da venda",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1.0, "O valor da venda não pode ser menor que R$ 1.00."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "A quantidade não pode ser menor que 1."
                    )
                ]
            ),
        ),
    ]
